-- return {
-- 	"nvim-neo-tree/neo-tree.nvim",
-- 	cmd = "Neotree",
-- 	dependencies = {
-- 		{
-- 			"s1n7ax/nvim-window-picker",
-- 			event = "VeryLazy",
-- 			config = function()
-- 				require("window-picker").setup({
-- 					autoselect_one = true,
-- 					include_current = false,
-- 					selection_chars = "TNSERIAO",
-- 					filter_rules = {
-- 						-- filter using buffer options
-- 						bo = {
-- 							-- if the file type is one of following, the window will be ignored
-- 							filetype = { "neo-tree", "neo-tree-popup", "notify", "edgy" },
--
-- 							-- if the buffer type is one of following, the window will be ignored
-- 							buftype = { "terminal", "quickfix" },
-- 						},
-- 					},
-- 					other_win_hl_color = "#e35e4f",
-- 				})
-- 			end,
-- 		},
-- 	},
-- 	keys = {
-- 		-- {
-- 		-- 	"<leader>fe",
-- 		-- 	function()
-- 		-- 		require("neo-tree.command").execute({ toggle = true, dir = require("user.utils").get_root() })
-- 		-- 	end,
-- 		-- 	desc = "Explorer NeoTree (root dir)",
-- 		-- },
-- 		{
-- 			"<leader>e",
-- 			function()
-- 				require("neo-tree.command").execute({ toggle = true, dir = vim.loop.cwd() })
-- 			end,
-- 			desc = "Explorer NeoTree (cwd)",
-- 		},
-- 		-- { "<leader>e", "<leader>fe", desc = "Explorer NeoTree (root dir)", remap = true },
-- 		-- { "<leader>E", "<leader>fE", desc = "Explorer NeoTree (cwd)", remap = true },
-- 	},
-- 	deactivate = function()
-- 		vim.cmd([[Neotree close]])
-- 	end,
-- 	init = function()
-- 		vim.g.neo_tree_remove_legacy_commands = 1
-- 		if vim.fn.argc() == 1 then
-- 			local stat = vim.loop.fs_stat(vim.fn.argv(0))
-- 			if stat and stat.type == "directory" then
-- 				require("neo-tree")
-- 			end
-- 		end
-- 	end,
-- 	opts = {
-- 		sources = { "filesystem", "buffers", "git_status", "document_symbols" },
-- 		open_files_do_not_replace_types = { "terminal", "Trouble", "qf", "edgy" },
--
-- 		filesystem = {
-- 			bind_to_cwd = false,
-- 			follow_current_file = true,
-- 			use_libuv_file_watcher = true,
-- 		},
-- 		window = {
-- 			mappings = {
-- 				["<space>"] = "none",
-- 			},
-- 		},
-- 		default_component_configs = {
-- 			indent = {
-- 				with_expanders = true, -- if nil and file nesting is enabled, will enable expanders
-- 				expander_collapsed = "",
-- 				expander_expanded = "",
-- 				expander_highlight = "NeoTreeExpander",
-- 			},
-- 		},
-- 	},
-- 	config = function(_, opts)
-- 		require("neo-tree").setup(opts)
-- 		vim.api.nvim_create_autocmd("TermClose", {
-- 			pattern = "*lazygit",
-- 			callback = function()
-- 				if package.loaded["neo-tree.sources.git_status"] then
-- 					require("neo-tree.sources.git_status").refresh()
-- 				end
-- 			end,
-- 		})
-- 	end,
-- }

return {}
