-- -- -- require("user.dap")
-- -- require("user.bufferline")


-- -- require("user.alpha")
-- require("user.auto-session")
-- require("user.bqf")
-- require("user.cheatsheet")
-- require("user.fidget")
-- require("user.icon-picker")
-- require("user.lsp")
-- -- require("user.lualine")
-- -- require("user.navic")
-- -- require("user.neo-tree")
-- require("user.neoscroll")
-- -- require("user.noice")
-- require("user.notify")
-- require("user.nvim-window-picker")
-- require("user.overseer")
-- require("user.rust_tools")
-- require("user.session-lens")
-- require("user.silicon")
-- require("user.spectre")
-- require("user.surround")
-- require("user.terminal")
-- require("user.todo-comments")
-- require("user.treesitter")
-- require("user.zen")

require("user.plugins")
require("user.plugins.leap")
require("user.plugins.telescope")
require("user.plugins.whichkey")

require("user.settings")
require("user.keymappings")
